#!/usr/bin/env python
# encoding: utf-8

name = "Seed"
shortDesc = u""
longDesc = u"""

"""
autoGenerated=True
entry(
    index = 0,
    label = "C7H10 <=> C1=CC2CCCC12",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (4.99998e+11, 's^-1'),
        n = 0.0559095,
        Ea = (122.413, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [1,3-butadiene_backbone;C=C_1;C=C_2] for rate rule [1,3-butadiene_backbone;CdH(C)_1;CdH(C)_2]\nEuclidian distance = 1.41421356237\nfamily: Intra_2+2_cycloaddition_Cd',
    ),
    longDesc = 
u"""
Estimated using template [1,3-butadiene_backbone;C=C_1;C=C_2] for rate rule [1,3-butadiene_backbone;CdH(C)_1;CdH(C)_2]
Euclidian distance = 1.41421356237
family: Intra_2+2_cycloaddition_Cd
""",
)

entry(
    index = 1,
    label = "[CH]1C=CC=CCC1 + [CH]1C=CCCCC1 <=> C7H10 + C7H10",
    degeneracy = 8.0,
    kinetics = Arrhenius(
        A = (6.104e+12, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (-2.3012, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad/H/Cd]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 8.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad/H/Cd]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 8.0
family: Disproportionation
""",
)

entry(
    index = 2,
    label = "O2 + [CH]1C=CC=CCC1 <=> [O]OC1C=CC=CCC1",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (1.06514e+08, 'm^3/(mol*s)'),
        n = 0.108445,
        Ea = (5.74998, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (303.03, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Estimated using template [C_rad/H/CdCs;Y_rad] for rate rule [C_rad/H/CdCs;O2_birad]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 4.0\nfamily: R_Recombination',
    ),
    longDesc = 
u"""
Estimated using template [C_rad/H/CdCs;Y_rad] for rate rule [C_rad/H/CdCs;O2_birad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: R_Recombination
""",
)

entry(
    index = 3,
    label = "O2 + [CH]1C=CCCCC1 <=> [O]OC1C=CCCCC1",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (1.06514e+08, 'm^3/(mol*s)'),
        n = 0.108445,
        Ea = (5.74998, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (303.03, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Estimated using template [C_rad/H/CdCs;Y_rad] for rate rule [C_rad/H/CdCs;O2_birad]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 4.0\nfamily: R_Recombination',
    ),
    longDesc = 
u"""
Estimated using template [C_rad/H/CdCs;Y_rad] for rate rule [C_rad/H/CdCs;O2_birad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: R_Recombination
""",
)

entry(
    index = 4,
    label = "[CH2]C=CC=CC[CH2] <=> C7H10",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (7.38971e+10, 's^-1'),
        n = 0.0476667,
        Ea = (8.08907, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [Rn;C_rad_out_2H;Cpri_rad_out_2H] for rate rule [R7;C_rad_out_2H;Cpri_rad_out_2H]\nEuclidian distance = 1.0\nfamily: Birad_recombination',
    ),
    longDesc = 
u"""
Estimated using template [Rn;C_rad_out_2H;Cpri_rad_out_2H] for rate rule [R7;C_rad_out_2H;Cpri_rad_out_2H]
Euclidian distance = 1.0
family: Birad_recombination
""",
)

entry(
    index = 5,
    label = "[CH2]C=CC=CC[CH2] <=> C=CC=CC1CC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (2e+12, 's^-1'),
        n = 0,
        Ea = (7.5312, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (550, 'K'),
        Tmax = (650, 'K'),
        comment = 'Estimated using template [Rn;C_rad_out_H/OneDe;Cpri_rad_out_2H] for rate rule [R3_SS;C_rad_out_H/OneDe;Cpri_rad_out_2H]\nEuclidian distance = 2.0\nfamily: Birad_recombination',
    ),
    longDesc = 
u"""
Estimated using template [Rn;C_rad_out_H/OneDe;Cpri_rad_out_2H] for rate rule [R3_SS;C_rad_out_H/OneDe;Cpri_rad_out_2H]
Euclidian distance = 2.0
family: Birad_recombination
""",
)

entry(
    index = 6,
    label = "[C]1CC=CCCC1 <=> C7H10",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (6.84965e+11, 's^-1'),
        n = 0.4135,
        Ea = (17.2276, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [singletcarbene_CH;CsJ2C;CH2(C=C)] for rate rule [CsJ2-C;CsJ2(CsC);CH2(C=C)]\nEuclidian distance = 1.41421356237\nMultiplied by reaction path degeneracy 2.0\nfamily: Singlet_Carbene_Intra_Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [singletcarbene_CH;CsJ2C;CH2(C=C)] for rate rule [CsJ2-C;CsJ2(CsC);CH2(C=C)]
Euclidian distance = 1.41421356237
Multiplied by reaction path degeneracy 2.0
family: Singlet_Carbene_Intra_Disproportionation
""",
)

entry(
    index = 7,
    label = "O2 + [CH]1C=CC=CCC1 <=> [O]OC1C=CCCC=C1",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (5.9277e+07, 'm^3/(mol*s)'),
        n = -0.00388889,
        Ea = (-0.926059, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [C_rad/H/CdCd;Y_rad] for rate rule [C_rad/H/CdCd;O2_birad]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 2.0\nfamily: R_Recombination',
    ),
    longDesc = 
u"""
Estimated using template [C_rad/H/CdCd;Y_rad] for rate rule [C_rad/H/CdCd;O2_birad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 8,
    label = "[CH2]C=CC=CC[CH2] <=> C=CC=CCC=C",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(
        A = (8.96625e+08, 's^-1'),
        n = 0.311,
        Ea = (39.225, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [R4;Y_rad_De;XH_Rrad] for rate rule [R4radExo;Y_rad_De;XH_Rrad]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 2.0\nfamily: Intra_Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [R4;Y_rad_De;XH_Rrad] for rate rule [R4radExo;Y_rad_De;XH_Rrad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Intra_Disproportionation
""",
)

entry(
    index = 9,
    label = "[CH2]C=CC=CC[CH2] <=> C=CC=CCC=C",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(
        A = (3.898e+11, 's^-1'),
        n = 0.486,
        Ea = (22.8614, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using an average for rate rule [R2radExo;Y_rad_De;XH_Rrad]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Intra_Disproportionation',
    ),
    longDesc = 
u"""
Estimated using an average for rate rule [R2radExo;Y_rad_De;XH_Rrad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Intra_Disproportionation
""",
)

entry(
    index = 10,
    label = "[CH2]C=CC=CC[CH2] <=> C=CC=CCC=C",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(
        A = (3.898e+11, 's^-1'),
        n = 0.486,
        Ea = (22.8614, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using an average for rate rule [R2radExo;Y_rad_De;XH_Rrad]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Intra_Disproportionation',
    ),
    longDesc = 
u"""
Estimated using an average for rate rule [R2radExo;Y_rad_De;XH_Rrad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Intra_Disproportionation
""",
)

entry(
    index = 11,
    label = "[CH2]C=CC=CC[CH2] <=> C=CC=CCC=C",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(
        A = (8.96625e+08, 's^-1'),
        n = 0.311,
        Ea = (39.225, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [R4;Y_rad_De;XH_Rrad] for rate rule [R4radExo;Y_rad_De;XH_Rrad]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 2.0\nfamily: Intra_Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [R4;Y_rad_De;XH_Rrad] for rate rule [R4radExo;Y_rad_De;XH_Rrad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Intra_Disproportionation
""",
)

entry(
    index = 12,
    label = "[O]OC1C=CCCCC1 <=> [CH]1CCCCC2OOC12",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (1.99832e+10, 's^-1'),
        n = 0.37247,
        Ea = (49.4918, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [R6plus;doublebond_intra_pri;radadd_intra] for rate rule [Rn2c7_alpha_long;doublebond_intra_pri;radadd_intra_O]\nEuclidian distance = 3.16227766017\nfamily: Intra_R_Add_Endocyclic',
    ),
    longDesc = 
u"""
Estimated using template [R6plus;doublebond_intra_pri;radadd_intra] for rate rule [Rn2c7_alpha_long;doublebond_intra_pri;radadd_intra_O]
Euclidian distance = 3.16227766017
family: Intra_R_Add_Endocyclic
""",
)

entry(
    index = 13,
    label = "[CH]1C=CC=CCC1 + C1=CCCC=CC1 <=> C7H10 + [CH]1C=CC=CCC1",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (0.003924, 'cm^3/(mol*s)'),
        n = 4.34,
        Ea = (26.3592, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'From training reaction 1132 used for C/H2/CdCd;C_rad/H/CdCs\nExact match found for rate rule [C/H2/CdCd;C_rad/H/CdCs]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 4.0\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
From training reaction 1132 used for C/H2/CdCd;C_rad/H/CdCs
Exact match found for rate rule [C/H2/CdCd;C_rad/H/CdCs]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: H_Abstraction
""",
)

entry(
    index = 14,
    label = "[CH]1C=CC=CCC1 + [CH]1C=CCCCC1 <=> C7H10 + C1=CCCC=CC1",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (0.0525937, 'm^3/(mol*s)'),
        n = 2,
        Ea = (2.38488, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [C_sec_rad;C/H2/Nd_Csrad] for rate rule [C_rad/H/TwoDe;C/H2/Nd_Csrad/H/Cd]\nEuclidian distance = 1.41421356237\nMultiplied by reaction path degeneracy 4.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [C_sec_rad;C/H2/Nd_Csrad] for rate rule [C_rad/H/TwoDe;C/H2/Nd_Csrad/H/Cd]
Euclidian distance = 1.41421356237
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
""",
)

entry(
    index = 15,
    label = "[C]1CC=CCCC1 <=> C1=CCCC=CC1",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (3.23663e+16, 's^-1'),
        n = -0.885455,
        Ea = (87.4392, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (303.03, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Estimated using template [CsJ2-C;CsJ2(CsC);CH] for rate rule [CsJ2-C;CsJ2(CsC);CH2(C)]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 2.0\nfamily: Singlet_Carbene_Intra_Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [CsJ2-C;CsJ2(CsC);CH] for rate rule [CsJ2-C;CsJ2(CsC);CH2(C)]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Singlet_Carbene_Intra_Disproportionation
""",
)

entry(
    index = 16,
    label = "[CH]1C=CC=CCC1 + [CH]1C=CC=CCC1 <=> C1=CC=CCC=C1 + C1=CCCC=CC1",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (0.0525937, 'm^3/(mol*s)'),
        n = 2,
        Ea = (2.38488, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [C_sec_rad;C/H2/Nd_Csrad] for rate rule [C_rad/H/TwoDe;C/H2/Nd_Csrad/H/Cd]\nEuclidian distance = 1.41421356237\nMultiplied by reaction path degeneracy 4.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [C_sec_rad;C/H2/Nd_Csrad] for rate rule [C_rad/H/TwoDe;C/H2/Nd_Csrad/H/Cd]
Euclidian distance = 1.41421356237
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
""",
)

entry(
    index = 17,
    label = "[CH]1C=CC=CCC1 + [CH]1C=CC=CCC1 <=> C7H10 + C1=CC=CCC=C1",
    degeneracy = 8.0,
    kinetics = Arrhenius(
        A = (6.104e+12, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (-2.3012, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad/H/Cd]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 8.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad/H/Cd]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 8.0
family: Disproportionation
""",
)

entry(
    index = 18,
    label = "C7H10 + [O]OC1C=CCCCC1 <=> [CH]1C=CC=CCC1 + OOC1C=CCCCC1",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (0.02964, 'cm^3/(mol*s)', '*|/', 3),
        n = 4.313,
        Ea = (33.5389, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (600, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Estimated using an average for rate rule [C/H2/CdCs;OOC]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 4.0\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
Estimated using an average for rate rule [C/H2/CdCs;OOC]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: H_Abstraction
""",
)

entry(
    index = 19,
    label = "[CH]1C=CCCCC1 + [O]OC1C=CCCCC1 <=> C7H10 + OOC1C=CCCCC1",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (9.64e+13, 'cm^3/(mol*s)', '*|/', 3),
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'Estimated using template [O_rad;C/H2/Nd_Csrad] for rate rule [O_rad/NonDeO;C/H2/Nd_Csrad/H/Cd]\nEuclidian distance = 2.2360679775\nMultiplied by reaction path degeneracy 4.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [O_rad;C/H2/Nd_Csrad] for rate rule [O_rad/NonDeO;C/H2/Nd_Csrad/H/Cd]
Euclidian distance = 2.2360679775
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
""",
)

entry(
    index = 20,
    label = "[CH]1C=CC=CCC1 + [O]OC1C=CCCCC1 <=> C1=CC=CCC=C1 + OOC1C=CCCCC1",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (9.64e+13, 'cm^3/(mol*s)', '*|/', 3),
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'Estimated using template [O_rad;C/H2/Nd_Csrad] for rate rule [O_rad/NonDeO;C/H2/Nd_Csrad/H/Cd]\nEuclidian distance = 2.2360679775\nMultiplied by reaction path degeneracy 4.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [O_rad;C/H2/Nd_Csrad] for rate rule [O_rad/NonDeO;C/H2/Nd_Csrad/H/Cd]
Euclidian distance = 2.2360679775
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
""",
)

entry(
    index = 21,
    label = "C1=CCCC=CC1 + [O]OC1C=CCCCC1 <=> [CH]1C=CC=CCC1 + OOC1C=CCCCC1",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (0.01482, 'cm^3/(mol*s)', '*|/', 3),
        n = 4.313,
        Ea = (33.5389, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (600, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Estimated using template [C_sec;OOC] for rate rule [C/H2/CdCd;OOC]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 2.0\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [C_sec;OOC] for rate rule [C/H2/CdCd;OOC]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 22,
    label = "[CH2]CCC=CC=C <=> [CH]1C=CCCCC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (114000, 's^-1'),
        n = 1.2,
        Ea = (27.196, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'From training reaction 46 used for R7_linear;doublebond_intra_pri_2H;radadd_intra_cs2H\nExact match found for rate rule [R7_linear;doublebond_intra_pri_2H;radadd_intra_cs2H]\nEuclidian distance = 0\nfamily: Intra_R_Add_Endocyclic',
    ),
    longDesc = 
u"""
From training reaction 46 used for R7_linear;doublebond_intra_pri_2H;radadd_intra_cs2H
Exact match found for rate rule [R7_linear;doublebond_intra_pri_2H;radadd_intra_cs2H]
Euclidian distance = 0
family: Intra_R_Add_Endocyclic
""",
)

entry(
    index = 23,
    label = "[CH]1C=CC=CCC1 + [CH2]CCC=CC=C <=> C7H10 + C=CC=CCC=C",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (3.052e+12, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (-2.3012, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 4.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
""",
)

entry(
    index = 24,
    label = "[CH]1C=CC=CCC1 + [CH2]CCC=CC=C <=> C=CC=CCC=C + C1=CCCC=CC1",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (319.424, 'm^3/(mol*s)'),
        n = 1,
        Ea = (1.94556, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using average of templates [C_sec_rad;C/H2/Nd_Csrad] + [C_rad/H/TwoDe;C/H2/Nd_Rrad] for rate rule [C_rad/H/TwoDe;C/H2/Nd_Csrad]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 2.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using average of templates [C_sec_rad;C/H2/Nd_Csrad] + [C_rad/H/TwoDe;C/H2/Nd_Rrad] for rate rule [C_rad/H/TwoDe;C/H2/Nd_Csrad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 25,
    label = "[CH2]CCC=CC=C + [O]OC1C=CCCCC1 <=> C=CC=CCC=C + OOC1C=CCCCC1",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (4.82e+13, 'cm^3/(mol*s)', '*|/', 3),
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'Estimated using template [O_rad;C/H2/Nd_Csrad] for rate rule [O_rad/NonDeO;C/H2/Nd_Csrad]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 2.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [O_rad;C/H2/Nd_Csrad] for rate rule [O_rad/NonDeO;C/H2/Nd_Csrad]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 26,
    label = "[CH2]C=CC=CC[CH2] + [CH]1C=CCCCC1 <=> C7H10 + [CH2]CCC=CC=C",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (3.052e+12, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (-2.3012, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad/H/Cd]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 4.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad/H/Cd]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
""",
)

entry(
    index = 27,
    label = "[CH2]C=CC=CC[CH2] + [CH2]CCC=CC=C <=> [CH2]CCC=CC=C + C=CC=CCC=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (1.526e+12, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (-2.3012, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 2.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 28,
    label = "[CH]1C=CC=CCC1 + [CH2]C=CC=CC[CH2] <=> C1=CC=CCC=C1 + [CH2]CCC=CC=C",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (3.052e+12, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (-2.3012, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad/H/Cd]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 4.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad/H/Cd]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
""",
)

entry(
    index = 29,
    label = "[CH2]C=CC=C + C=C <=> [CH2]CCC=CC=C",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (2700, 'cm^3/(mol*s)', '*|/', 2),
        n = 2.7,
        Ea = (47.2792, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'From training reaction 3 used for Cds-HH_Cds-HH;CsJ-CdHH\nExact match found for rate rule [Cds-HH_Cds-HH;CsJ-CdHH]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 4.0\nfamily: R_Addition_MultipleBond',
    ),
    longDesc = 
u"""
From training reaction 3 used for Cds-HH_Cds-HH;CsJ-CdHH
Exact match found for rate rule [Cds-HH_Cds-HH;CsJ-CdHH]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: R_Addition_MultipleBond
""",
)

entry(
    index = 30,
    label = "O2 + [CH2]C=CC=C <=> C=CC(C=C)O[O]",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (5.9277e+07, 'm^3/(mol*s)'),
        n = -0.00388889,
        Ea = (-0.926059, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [C_rad/H/CdCd;Y_rad] for rate rule [C_rad/H/CdCd;O2_birad]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 2.0\nfamily: R_Recombination',
    ),
    longDesc = 
u"""
Estimated using template [C_rad/H/CdCd;Y_rad] for rate rule [C_rad/H/CdCd;O2_birad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 31,
    label = "O2 + [CH2]C=CC=C <=> C=CC=CCO[O]",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (235062, 'm^3/(mol*s)'),
        n = 0.534092,
        Ea = (0.273537, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using average of templates [C_pri_rad;O2_birad] + [C_rad/H2/Cd;Y_rad] for rate rule [C_rad/H2/Cd;O2_birad]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 4.0\nfamily: R_Recombination',
    ),
    longDesc = 
u"""
Estimated using average of templates [C_pri_rad;O2_birad] + [C_rad/H2/Cd;Y_rad] for rate rule [C_rad/H2/Cd;O2_birad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: R_Recombination
""",
)

entry(
    index = 32,
    label = "[O]OC1C=CCCC=C1 <=> [CH]1CCC=CC2OOC12",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (3.99665e+10, 's^-1'),
        n = 0.37247,
        Ea = (49.4918, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [R6plus;doublebond_intra_pri;radadd_intra] for rate rule [Rn2c7_alpha_long;doublebond_intra_pri;radadd_intra_O]\nEuclidian distance = 3.16227766017\nMultiplied by reaction path degeneracy 2.0\nfamily: Intra_R_Add_Endocyclic',
    ),
    longDesc = 
u"""
Estimated using template [R6plus;doublebond_intra_pri;radadd_intra] for rate rule [Rn2c7_alpha_long;doublebond_intra_pri;radadd_intra_O]
Euclidian distance = 3.16227766017
Multiplied by reaction path degeneracy 2.0
family: Intra_R_Add_Endocyclic
""",
)

entry(
    index = 33,
    label = "C7H10 + [CH2]C=CC=C <=> [CH]1C=CC=CCC1 + C=CC=CC",
    degeneracy = 8.0,
    kinetics = Arrhenius(
        A = (0.03616, 'cm^3/(mol*s)'),
        n = 4.34,
        Ea = (46.8608, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'Estimated using an average for rate rule [C/H2/CdCs;C_rad/H2/Cd\\H_Cd\\H2]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 8.0\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
Estimated using an average for rate rule [C/H2/CdCs;C_rad/H2/Cd\H_Cd\H2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 8.0
family: H_Abstraction
""",
)

entry(
    index = 34,
    label = "[CH2]C=CC=C + [CH]1C=CCCCC1 <=> C7H10 + C=CC=CC",
    degeneracy = 8.0,
    kinetics = Arrhenius(
        A = (1.16e+13, 'cm^3/(mol*s)', '*|/', 3),
        n = 0,
        Ea = (-0.54392, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'Estimated using template [C_rad/H2/Cd;C/H2/Nd_Csrad] for rate rule [C_rad/H2/Cd;C/H2/Nd_Csrad/H/Cd]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 8.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [C_rad/H2/Cd;C/H2/Nd_Csrad] for rate rule [C_rad/H2/Cd;C/H2/Nd_Csrad/H/Cd]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 8.0
family: Disproportionation
""",
)

entry(
    index = 35,
    label = "[CH]1C=CC=CCC1 + [CH2]C=CC=C <=> C1=CC=CCC=C1 + C=CC=CC",
    degeneracy = 8.0,
    kinetics = Arrhenius(
        A = (1.16e+13, 'cm^3/(mol*s)', '*|/', 3),
        n = 0,
        Ea = (-0.54392, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'Estimated using template [C_rad/H2/Cd;C/H2/Nd_Csrad] for rate rule [C_rad/H2/Cd;C/H2/Nd_Csrad/H/Cd]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 8.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [C_rad/H2/Cd;C/H2/Nd_Csrad] for rate rule [C_rad/H2/Cd;C/H2/Nd_Csrad/H/Cd]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 8.0
family: Disproportionation
""",
)

entry(
    index = 36,
    label = "[CH2]C=CC=C + C1=CCCC=CC1 <=> [CH]1C=CC=CCC1 + C=CC=CC",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (0.00772, 'cm^3/(mol*s)'),
        n = 4.34,
        Ea = (28.0328, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'From training reaction 1131 used for C/H2/CdCd;C_rad/H2/Cd\\H_Cd\\H2\nExact match found for rate rule [C/H2/CdCd;C_rad/H2/Cd\\H_Cd\\H2]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 4.0\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
From training reaction 1131 used for C/H2/CdCd;C_rad/H2/Cd\H_Cd\H2
Exact match found for rate rule [C/H2/CdCd;C_rad/H2/Cd\H_Cd\H2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: H_Abstraction
""",
)

entry(
    index = 37,
    label = "[O]OC1C=CCCCC1 + C=CC=CC <=> [CH2]C=CC=C + OOC1C=CCCCC1",
    degeneracy = 3.0,
    kinetics = Arrhenius(
        A = (1.73499e-09, 'm^3/(mol*s)'),
        n = 4.65,
        Ea = (40.9195, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [C/H3/Cd;O_rad/NonDeO] for rate rule [C/H3/Cd;OOC]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 3.0\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [C/H3/Cd;O_rad/NonDeO] for rate rule [C/H3/Cd;OOC]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 3.0
family: H_Abstraction
""",
)

entry(
    index = 38,
    label = "[CH2]C=CC=C + [CH2]CCC=CC=C <=> C=CC=CCC=C + C=CC=CC",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (5.8e+12, 'cm^3/(mol*s)', '*|/', 3),
        n = 0,
        Ea = (-0.54392, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'From training reaction 23 used for C_rad/H2/Cd;C/H2/Nd_Csrad\nExact match found for rate rule [C_rad/H2/Cd;C/H2/Nd_Csrad]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 4.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
From training reaction 23 used for C_rad/H2/Cd;C/H2/Nd_Csrad
Exact match found for rate rule [C_rad/H2/Cd;C/H2/Nd_Csrad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
""",
)

entry(
    index = 39,
    label = "[CH]1C=CCCCC1 + [O]OC1C=C[CH]CC=C1 <=> C7H10 + [O]OC1C=CCCC=C1",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (3.052e+12, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (-2.3012, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad/H/Cd]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 4.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad/H/Cd]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
""",
)

entry(
    index = 40,
    label = "[O]OC1C=C[CH]CC=C1 + C1=CCCC=CC1 <=> [CH]1C=CC=CCC1 + [O]OC1C=CCCC=C1",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (0.001962, 'cm^3/(mol*s)'),
        n = 4.34,
        Ea = (26.9142, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'From training reaction 1132 used for C/H2/CdCd;C_rad/H/CdCs\nExact match found for rate rule [C/H2/CdCd;C_rad/H/CdCs]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
From training reaction 1132 used for C/H2/CdCd;C_rad/H/CdCs
Exact match found for rate rule [C/H2/CdCd;C_rad/H/CdCs]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 41,
    label = "[CH]1C=CC=CCC1 + [O]OC1C=CCCC=C1 <=> C7H10 + [O]OC1C=C[CH]CC=C1",
    degeneracy = 8.0,
    kinetics = Arrhenius(
        A = (0.01832, 'cm^3/(mol*s)'),
        n = 4.34,
        Ea = (48.9528, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'Estimated using an average for rate rule [C/H2/CdCs;C_rad/H/CdCs]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 8.0\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
Estimated using an average for rate rule [C/H2/CdCs;C_rad/H/CdCs]
Euclidian distance = 0
Multiplied by reaction path degeneracy 8.0
family: H_Abstraction
""",
)

entry(
    index = 42,
    label = "[CH2]CCC=CC=C + [O]OC1C=C[CH]CC=C1 <=> C=CC=CCC=C + [O]OC1C=CCCC=C1",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (1.526e+12, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (-2.3012, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 2.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 43,
    label = "O2 + C1=CC=CCC=C1 <=> [O]OC1C=C[CH]CC=C1",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (1.34733, 'm^3/(mol*s)'),
        n = 2.2488,
        Ea = (54.3182, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [Cds-CdH_Cds-CdH;YJ] for rate rule [Cds-CdH_Cds-CdH;O2b]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 4.0\nfamily: R_Addition_MultipleBond\nEa raised from 40.3 to 54.3 kJ/mol to match endothermicity of reaction.',
    ),
    longDesc = 
u"""
Estimated using template [Cds-CdH_Cds-CdH;YJ] for rate rule [Cds-CdH_Cds-CdH;O2b]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 4.0
family: R_Addition_MultipleBond
Ea raised from 40.3 to 54.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 44,
    label = "[CH]1C=CC=CCC1 + [O]OC1C=C[CH]CC=C1 <=> C1=CC=CCC=C1 + [O]OC1C=CCCC=C1",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (3.052e+12, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (-2.3012, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad/H/Cd]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 4.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [C_rad/H/OneDeC;C/H2/Nd_Rrad] for rate rule [C_rad/H/OneDeC;C/H2/Nd_Csrad/H/Cd]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
""",
)

entry(
    index = 45,
    label = "C1=CC=CCC=C1 <=> C1=CC2C=CC2C1",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (9.99996e+11, 's^-1'),
        n = 0.0559095,
        Ea = (122.413, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [1,3-butadiene_backbone;C=C_1;C=C_2] for rate rule [1,3-butadiene_backbone;CdH(C)_1;CdH(C)_2]\nEuclidian distance = 1.41421356237\nMultiplied by reaction path degeneracy 2.0\nfamily: Intra_2+2_cycloaddition_Cd',
    ),
    longDesc = 
u"""
Estimated using template [1,3-butadiene_backbone;C=C_1;C=C_2] for rate rule [1,3-butadiene_backbone;CdH(C)_1;CdH(C)_2]
Euclidian distance = 1.41421356237
Multiplied by reaction path degeneracy 2.0
family: Intra_2+2_cycloaddition_Cd
""",
)

entry(
    index = 46,
    label = "[CH2]C=CC=C + [CH2]C=CC=C <=> C=CC(C=C)C(C=C)C=C",
    degeneracy = 0.5,
    kinetics = Arrhenius(
        A = (2.5e+07, 'm^3/(mol*s)'),
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using an average for rate rule [C_rad/H/CdCd;C_rad/H/CdCd]\nEuclidian distance = 0\nfamily: R_Recombination',
    ),
    longDesc = 
u"""
Estimated using an average for rate rule [C_rad/H/CdCd;C_rad/H/CdCd]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 47,
    label = "[CH2]C=CC=C + [CH2]C=CC=C <=> C=CC=CCC(C=C)C=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (2.04e+13, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (-1.08784, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'From training reaction 130 used for C_rad/H2/Cd;C_rad/H/CdCd\nExact match found for rate rule [C_rad/H/CdCd;C_rad/H2/Cd]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: R_Recombination',
    ),
    longDesc = 
u"""
From training reaction 130 used for C_rad/H2/Cd;C_rad/H/CdCd
Exact match found for rate rule [C_rad/H/CdCd;C_rad/H2/Cd]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 48,
    label = "[CH2]C=CC=C + [CH2]C=CC=C <=> C=CC=CCCC=CC=C",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (2.04e+13, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (-1.08784, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'From training reaction 125 used for C_rad/H2/Cd;C_rad/H2/Cd\nExact match found for rate rule [C_rad/H2/Cd;C_rad/H2/Cd]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: R_Recombination',
    ),
    longDesc = 
u"""
From training reaction 125 used for C_rad/H2/Cd;C_rad/H2/Cd
Exact match found for rate rule [C_rad/H2/Cd;C_rad/H2/Cd]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 49,
    label = "C=CC(C=C)C(C=C)C=C <=> C=CC=CCCC=CC=C",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (2.48474e+11, 's^-1'),
        n = 0.288169,
        Ea = (147.049, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [1_5_unsaturated_hexane] for rate rule [1_5_hexadiene]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 4.0\nfamily: 6_membered_central_C-C_shift',
    ),
    longDesc = 
u"""
Estimated using template [1_5_unsaturated_hexane] for rate rule [1_5_hexadiene]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: 6_membered_central_C-C_shift
""",
)

entry(
    index = 50,
    label = "C=CC=CCC=C <=> C=CCC1C=CC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (4.99998e+11, 's^-1'),
        n = 0.0559095,
        Ea = (122.413, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [1,3-butadiene_backbone;C=C_1;C=C_2] for rate rule [1,3-butadiene_backbone;CdH(C)_1;CdH2_2]\nEuclidian distance = 1.41421356237\nfamily: Intra_2+2_cycloaddition_Cd',
    ),
    longDesc = 
u"""
Estimated using template [1,3-butadiene_backbone;C=C_1;C=C_2] for rate rule [1,3-butadiene_backbone;CdH(C)_1;CdH2_2]
Euclidian distance = 1.41421356237
family: Intra_2+2_cycloaddition_Cd
""",
)

entry(
    index = 51,
    label = "C=CC=CC1CC1 <=> C1=CC(C1)C1CC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (4.99998e+11, 's^-1'),
        n = 0.0559095,
        Ea = (122.413, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [1,3-butadiene_backbone;C=C_1;C=C_2] for rate rule [1,3-butadiene_backbone;CdH(C)_1;CdH2_2]\nEuclidian distance = 1.41421356237\nfamily: Intra_2+2_cycloaddition_Cd',
    ),
    longDesc = 
u"""
Estimated using template [1,3-butadiene_backbone;C=C_1;C=C_2] for rate rule [1,3-butadiene_backbone;CdH(C)_1;CdH2_2]
Euclidian distance = 1.41421356237
family: Intra_2+2_cycloaddition_Cd
""",
)

entry(
    index = 52,
    label = "[O]C1C=CCCCC1 + OH(D) <=> OOC1C=CCCCC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (2e+13, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'From training reaction 103 used for O_pri_rad;O_rad/NonDe\nExact match found for rate rule [O_pri_rad;O_rad/NonDe]\nEuclidian distance = 0\nfamily: R_Recombination',
    ),
    longDesc = 
u"""
From training reaction 103 used for O_pri_rad;O_rad/NonDe
Exact match found for rate rule [O_pri_rad;O_rad/NonDe]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 53,
    label = "[CH2]CCCC=CC=O <=> [O]C1C=CCCCC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (1.19e+11, 's^-1'),
        n = 0.08,
        Ea = (69.8728, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [R8;multiplebond_intra;radadd_intra_cs2H] for rate rule [R8;carbonylbond_intra_H;radadd_intra_cs2H]\nEuclidian distance = 2.0\nfamily: Intra_R_Add_Exocyclic',
    ),
    longDesc = 
u"""
Estimated using template [R8;multiplebond_intra;radadd_intra_cs2H] for rate rule [R8;carbonylbond_intra_H;radadd_intra_cs2H]
Euclidian distance = 2.0
family: Intra_R_Add_Exocyclic
""",
)

entry(
    index = 54,
    label = "[CH2]CCCC=CC=O <=> O=C[CH]C1CCCC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (1.3294e+07, 's^-1'),
        n = 0.933333,
        Ea = (21.0943, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [R6_SSS_D;doublebond_intra;radadd_intra_cs2H] for rate rule [R6_SSS_D;doublebond_intra_HDe_pri;radadd_intra_cs2H]\nEuclidian distance = 2.0\nfamily: Intra_R_Add_Exocyclic',
    ),
    longDesc = 
u"""
Estimated using template [R6_SSS_D;doublebond_intra;radadd_intra_cs2H] for rate rule [R6_SSS_D;doublebond_intra_HDe_pri;radadd_intra_cs2H]
Euclidian distance = 2.0
family: Intra_R_Add_Exocyclic
""",
)

entry(
    index = 55,
    label = "O2 + O=C[CH]C1CCCC1 <=> [O]OC(C=O)C1CCCC1",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (3.1325e+07, 'm^3/(mol*s)'),
        n = 0.0120974,
        Ea = (2.94816, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [C_rad/H/OneDeC;Y_rad] for rate rule [C_rad/H/OneDeC;O2_birad]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 2.0\nfamily: R_Recombination',
    ),
    longDesc = 
u"""
Estimated using template [C_rad/H/OneDeC;Y_rad] for rate rule [C_rad/H/OneDeC;O2_birad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 56,
    label = "O=CCC1C[CH]CC1 <=> O=C[CH]C1CCCC1",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (0.502, 's^-1'),
        n = 3.86,
        Ea = (41.6308, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'Estimated using template [R4H_SSS;C_rad_out_H/NonDeC;Cs_H_out_H/OneDe] for rate rule [R4H_SSS;C_rad_out_H/NonDeC;Cs_H_out_H/CO]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 2.0\nfamily: intra_H_migration',
    ),
    longDesc = 
u"""
Estimated using template [R4H_SSS;C_rad_out_H/NonDeC;Cs_H_out_H/OneDe] for rate rule [R4H_SSS;C_rad_out_H/NonDeC;Cs_H_out_H/CO]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: intra_H_migration
""",
)

entry(
    index = 57,
    label = "C7H10 + OH(D) <=> [CH]1C=CC=CCC1 + H2O",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (134, 'cm^3/(mol*s)'),
        n = 3.475,
        Ea = (-11.7152, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'Estimated using an average for rate rule [C/H2/CdCs;O_pri_rad]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 4.0\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
Estimated using an average for rate rule [C/H2/CdCs;O_pri_rad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: H_Abstraction
""",
)

entry(
    index = 58,
    label = "[CH]1C=CC=CCC1 + OH(D) <=> C1=CC=CCC=C1 + H2O",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (9.64e+13, 'cm^3/(mol*s)', '*|/', 3),
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'Estimated using template [O_pri_rad;C/H2/Nd_Csrad] for rate rule [O_pri_rad;C/H2/Nd_Csrad/H/Cd]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 4.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [O_pri_rad;C/H2/Nd_Csrad] for rate rule [O_pri_rad;C/H2/Nd_Csrad/H/Cd]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
""",
)

entry(
    index = 59,
    label = "C1=CCCC=CC1 + OH(D) <=> [CH]1C=CC=CCC1 + H2O",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (9.16971e-06, 'm^3/(mol*s)'),
        n = 3.61325,
        Ea = (-3.94634, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using average of templates [C_sec;O_pri_rad] + [C/H2/CdCd;Y_rad] for rate rule [C/H2/CdCd;O_pri_rad]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 2.0\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
Estimated using average of templates [C_sec;O_pri_rad] + [C/H2/CdCd;Y_rad] for rate rule [C/H2/CdCd;O_pri_rad]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 60,
    label = "C=CC=CC + OH(D) <=> [CH2]C=CC=C + H2O",
    degeneracy = 3.0,
    kinetics = Arrhenius(
        A = (6.04483e-06, 'm^3/(mol*s)'),
        n = 3.684,
        Ea = (-5.35552, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using an average for rate rule [C/H3/Cd;O_pri_rad]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 3.0\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
Estimated using an average for rate rule [C/H3/Cd;O_pri_rad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: H_Abstraction
""",
)

entry(
    index = 61,
    label = "[CH]1C=CCCCC1 + OH(D) <=> C7H10 + H2O",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (9.64e+13, 'cm^3/(mol*s)', '*|/', 3),
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'Estimated using template [O_pri_rad;C/H2/Nd_Csrad] for rate rule [O_pri_rad;C/H2/Nd_Csrad/H/Cd]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 4.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [O_pri_rad;C/H2/Nd_Csrad] for rate rule [O_pri_rad;C/H2/Nd_Csrad/H/Cd]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
""",
)

entry(
    index = 62,
    label = "OH(D) + OOC1C=CCCCC1 <=> [O]OC1C=CCCCC1 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (1.1e+12, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (-1.82841, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'From training reaction 206 used for O/H/NonDeO;O_pri_rad\nExact match found for rate rule [O/H/NonDeO;O_pri_rad]\nEuclidian distance = 0\nfamily: H_Abstraction\nEa raised from -1.8 to -1.8 kJ/mol.',
    ),
    longDesc = 
u"""
From training reaction 206 used for O/H/NonDeO;O_pri_rad
Exact match found for rate rule [O/H/NonDeO;O_pri_rad]
Euclidian distance = 0
family: H_Abstraction
Ea raised from -1.8 to -1.8 kJ/mol.
""",
)

entry(
    index = 63,
    label = "[CH2]CCC=CC=C + OH(D) <=> C=CC=CCC=C + H2O",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (4.82e+13, 'cm^3/(mol*s)', '*|/', 3),
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'From training reaction 33 used for O_pri_rad;C/H2/Nd_Csrad\nExact match found for rate rule [O_pri_rad;C/H2/Nd_Csrad]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
From training reaction 33 used for O_pri_rad;C/H2/Nd_Csrad
Exact match found for rate rule [O_pri_rad;C/H2/Nd_Csrad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 64,
    label = "O2 + O=CCC1C[CH]CC1 <=> [O]OC1CCC(CC=O)C1",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (7.54e+12, 'cm^3/(mol*s)', '+|-', 1e+12),
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (1500, 'K'),
        comment = 'From training reaction 112 used for O2_birad;C_rad/H/NonDeC\nExact match found for rate rule [C_rad/H/NonDeC;O2_birad]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: R_Recombination',
    ),
    longDesc = 
u"""
From training reaction 112 used for O2_birad;C_rad/H/NonDeC
Exact match found for rate rule [C_rad/H/NonDeC;O2_birad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 65,
    label = "C7H10 + [O]OC(C=O)C1CCCC1 <=> [CH]1C=CC=CCC1 + O=CC(OO)C1CCCC1",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (0.02964, 'cm^3/(mol*s)', '*|/', 3),
        n = 4.313,
        Ea = (33.5389, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (600, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Estimated using an average for rate rule [C/H2/CdCs;OOC]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 4.0\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
Estimated using an average for rate rule [C/H2/CdCs;OOC]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: H_Abstraction
""",
)

entry(
    index = 66,
    label = "[CH]1C=CCCCC1 + [O]OC(C=O)C1CCCC1 <=> C7H10 + O=CC(OO)C1CCCC1",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (9.64e+13, 'cm^3/(mol*s)', '*|/', 3),
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'Estimated using template [O_rad;C/H2/Nd_Csrad] for rate rule [O_rad/NonDeO;C/H2/Nd_Csrad/H/Cd]\nEuclidian distance = 2.2360679775\nMultiplied by reaction path degeneracy 4.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [O_rad;C/H2/Nd_Csrad] for rate rule [O_rad/NonDeO;C/H2/Nd_Csrad/H/Cd]
Euclidian distance = 2.2360679775
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
""",
)

entry(
    index = 67,
    label = "[CH]1C=CC=CCC1 + [O]OC(C=O)C1CCCC1 <=> C1=CC=CCC=C1 + O=CC(OO)C1CCCC1",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (9.64e+13, 'cm^3/(mol*s)', '*|/', 3),
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (300, 'K'),
        Tmax = (2500, 'K'),
        comment = 'Estimated using template [O_rad;C/H2/Nd_Csrad] for rate rule [O_rad/NonDeO;C/H2/Nd_Csrad/H/Cd]\nEuclidian distance = 2.2360679775\nMultiplied by reaction path degeneracy 4.0\nfamily: Disproportionation',
    ),
    longDesc = 
u"""
Estimated using template [O_rad;C/H2/Nd_Csrad] for rate rule [O_rad/NonDeO;C/H2/Nd_Csrad/H/Cd]
Euclidian distance = 2.2360679775
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
""",
)

entry(
    index = 68,
    label = "C1=CCCC=CC1 + [O]OC(C=O)C1CCCC1 <=> [CH]1C=CC=CCC1 + O=CC(OO)C1CCCC1",
    degeneracy = 2.0,
    kinetics = Arrhenius(
        A = (0.01482, 'cm^3/(mol*s)', '*|/', 3),
        n = 4.313,
        Ea = (33.5389, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (600, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Estimated using template [C_sec;OOC] for rate rule [C/H2/CdCd;OOC]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 2.0\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [C_sec;OOC] for rate rule [C/H2/CdCd;OOC]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 69,
    label = "[O]OC1C=CCCCC1 + O=CC(OO)C1CCCC1 <=> OOC1C=CCCCC1 + [O]OC(C=O)C1CCCC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (0.092, 'cm^3/(mol*s)', '*|/', 3),
        n = 3.96,
        Ea = (27.7399, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (600, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Estimated using an average for rate rule [O/H/NonDeO;OOC]\nEuclidian distance = 0\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
Estimated using an average for rate rule [O/H/NonDeO;OOC]
Euclidian distance = 0
family: H_Abstraction
""",
)

entry(
    index = 70,
    label = "C=CC=CC + [O]OC(C=O)C1CCCC1 <=> [CH2]C=CC=C + O=CC(OO)C1CCCC1",
    degeneracy = 3.0,
    kinetics = Arrhenius(
        A = (1.73499e-09, 'm^3/(mol*s)'),
        n = 4.65,
        Ea = (40.9195, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'Estimated using template [C/H3/Cd;O_rad/NonDeO] for rate rule [C/H3/Cd;OOC]\nEuclidian distance = 1.0\nMultiplied by reaction path degeneracy 3.0\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [C/H3/Cd;O_rad/NonDeO] for rate rule [C/H3/Cd;OOC]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 3.0
family: H_Abstraction
""",
)

entry(
    index = 71,
    label = "[O]OC1C=CCCC=C1 + [O]OC(C=O)C1CCCC1 <=> [O]OC1C=C[CH]CC=C1 + O=CC(OO)C1CCCC1",
    degeneracy = 4.0,
    kinetics = Arrhenius(
        A = (0.02964, 'cm^3/(mol*s)', '*|/', 3),
        n = 4.313,
        Ea = (33.5389, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (600, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Estimated using an average for rate rule [C/H2/CdCs;OOC]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 4.0\nfamily: H_Abstraction',
    ),
    longDesc = 
u"""
Estimated using an average for rate rule [C/H2/CdCs;OOC]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: H_Abstraction
""",
)

entry(
    index = 72,
    label = "OH(D) + O=CC(OO)C1CCCC1 <=> H2O + [O]OC(C=O)C1CCCC1",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (1.1e+12, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (-1.82841, 'kJ/mol'),
        T0 = (1, 'K'),
        comment = 'From training reaction 206 used for O/H/NonDeO;O_pri_rad\nExact match found for rate rule [O/H/NonDeO;O_pri_rad]\nEuclidian distance = 0\nfamily: H_Abstraction\nEa raised from -1.8 to -1.8 kJ/mol.',
    ),
    longDesc = 
u"""
From training reaction 206 used for O/H/NonDeO;O_pri_rad
Exact match found for rate rule [O/H/NonDeO;O_pri_rad]
Euclidian distance = 0
family: H_Abstraction
Ea raised from -1.8 to -1.8 kJ/mol.
""",
)

