#!/usr/bin/env python
# encoding: utf-8

name = "Seed"
shortDesc = u""
longDesc = u"""

"""
autoGenerated=True
entry(
    index = 0,
    label = "O2 + H <=> O + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.04e+14, 'cm^3/(mol*s)'), n=0, Ea=(15286, 'cal/mol'), T0=(1, 'K')),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 1,
    label = "O + H2 <=> H + OH",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = MultiArrhenius(
        arrhenius = [
            Arrhenius(A=(3.818e+12, 'cm^3/(mol*s)'), n=0, Ea=(7948, 'cal/mol'), T0=(1, 'K')),
            Arrhenius(
                A = (8.792e+14, 'cm^3/(mol*s)'),
                n = 0,
                Ea = (19170, 'cal/mol'),
                T0 = (1, 'K'),
            ),
        ],
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 2,
    label = "OH + H2 <=> H + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (2.16e+08, 'cm^3/(mol*s)'),
        n = 1.51,
        Ea = (3430, 'cal/mol'),
        T0 = (1, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 3,
    label = "OH + OH <=> O + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(33400, 'cm^3/(mol*s)'), n=2.42, Ea=(-1930, 'cal/mol'), T0=(1, 'K')),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 4,
    label = "H2 <=> H + H",
    degeneracy = 1.0,
    kinetics = ThirdBody(
        arrheniusLow = Arrhenius(
            A = (4.577e+19, 'cm^3/(mol*s)'),
            n = -1.4,
            Ea = (104380, 'cal/mol'),
            T0 = (1, 'K'),
        ),
        efficiencies = {'O=C=O': 3.8, 'O': 12, '[H][H]': 2.5, '[He]': 0, '[C-]#[O+]': 1.9, '[Ar]': 0},
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 5,
    label = "H2 + Ar <=> H + H + Ar",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (5.84e+18, 'cm^3/(mol*s)'),
        n = -1.1,
        Ea = (104380, 'cal/mol'),
        T0 = (1, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 6,
    label = "H2 + He <=> H + H + He",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (5.84e+18, 'cm^3/(mol*s)'),
        n = -1.1,
        Ea = (104380, 'cal/mol'),
        T0 = (1, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 7,
    label = "O + O <=> O2",
    degeneracy = 1.0,
    kinetics = ThirdBody(
        arrheniusLow = Arrhenius(
            A = (6.165e+15, 'cm^6/(mol^2*s)'),
            n = -0.5,
            Ea = (0, 'cal/mol'),
            T0 = (1, 'K'),
        ),
        efficiencies = {'O=C=O': 3.8, 'O': 12, '[H][H]': 2.5, '[He]': 0, '[C-]#[O+]': 1.9, '[Ar]': 0},
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 8,
    label = "O + O + Ar <=> O2 + Ar",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (1.886e+13, 'cm^6/(mol^2*s)'),
        n = 0,
        Ea = (-1788, 'cal/mol'),
        T0 = (1, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 9,
    label = "O + O + He <=> O2 + He",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (1.886e+13, 'cm^6/(mol^2*s)'),
        n = 0,
        Ea = (-1788, 'cal/mol'),
        T0 = (1, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 10,
    label = "H + O <=> OH",
    degeneracy = 1.0,
    kinetics = ThirdBody(
        arrheniusLow = Arrhenius(A=(4.714e+18, 'cm^6/(mol^2*s)'), n=-1, Ea=(0, 'cal/mol'), T0=(1, 'K')),
        efficiencies = {'O=C=O': 3.8, 'O': 12, '[H][H]': 2.5, '[He]': 0.75, '[C-]#[O+]': 1.9, '[Ar]': 0.75},
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 11,
    label = "H2O <=> H + OH",
    degeneracy = 1.0,
    kinetics = ThirdBody(
        arrheniusLow = Arrhenius(
            A = (6.064e+27, 'cm^3/(mol*s)'),
            n = -3.322,
            Ea = (120790, 'cal/mol'),
            T0 = (1, 'K'),
        ),
        efficiencies = {'O=C=O': 3.8, 'O': 0, '[H][H]': 3, '[He]': 1.1, '[O][O]': 1.5, 'N#N': 2, '[C-]#[O+]': 1.9},
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 12,
    label = "H2O + H2O <=> H + OH + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (1.006e+26, 'cm^3/(mol*s)'),
        n = -2.44,
        Ea = (120180, 'cal/mol'),
        T0 = (1, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 13,
    label = "O2 + H <=> HO2",
    degeneracy = 1.0,
    kinetics = Troe(
        arrheniusHigh = Arrhenius(
            A = (4.65084e+12, 'cm^3/(mol*s)'),
            n = 0.44,
            Ea = (0, 'cal/mol'),
            T0 = (1, 'K'),
        ),
        arrheniusLow = Arrhenius(
            A = (6.366e+20, 'cm^6/(mol^2*s)'),
            n = -1.72,
            Ea = (524.8, 'cal/mol'),
            T0 = (1, 'K'),
        ),
        alpha = 0.5,
        T3 = (1e-30, 'K'),
        T1 = (1e+30, 'K'),
        efficiencies = {'O=C=O': 3.8, 'O': 14, '[H][H]': 2, '[He]': 0.8, '[O][O]': 0.78, '[C-]#[O+]': 1.9, '[Ar]': 0.67},
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 14,
    label = "H + HO2 <=> O2 + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (2.75e+06, 'cm^3/(mol*s)'),
        n = 2.09,
        Ea = (-1451, 'cal/mol'),
        T0 = (1, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 15,
    label = "H + HO2 <=> OH + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.079e+13, 'cm^3/(mol*s)'), n=0, Ea=(295, 'cal/mol'), T0=(1, 'K')),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 16,
    label = "O + HO2 <=> O2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (2.85e+10, 'cm^3/(mol*s)'),
        n = 1,
        Ea = (-723.93, 'cal/mol'),
        T0 = (1, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 17,
    label = "OH + HO2 <=> O2 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.89e+13, 'cm^3/(mol*s)'), n=0, Ea=(-497, 'cal/mol'), T0=(1, 'K')),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 18,
    label = "HO2 + HO2 <=> O2 + H2O2",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = MultiArrhenius(
        arrhenius = [
            Arrhenius(A=(4.2e+14, 'cm^3/(mol*s)'), n=0, Ea=(11982, 'cal/mol'), T0=(1, 'K')),
            Arrhenius(
                A = (1.3e+11, 'cm^3/(mol*s)'),
                n = 0,
                Ea = (-1629.3, 'cal/mol'),
                T0 = (1, 'K'),
            ),
        ],
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 19,
    label = "H2O2 <=> OH + OH",
    degeneracy = 1.0,
    kinetics = Troe(
        arrheniusHigh = Arrhenius(A=(2e+12, 's^-1'), n=0.9, Ea=(48749, 'cal/mol'), T0=(1, 'K')),
        arrheniusLow = Arrhenius(
            A = (2.49e+24, 'cm^3/(mol*s)'),
            n = -2.3,
            Ea = (48749, 'cal/mol'),
            T0 = (1, 'K'),
        ),
        alpha = 0.43,
        T3 = (1e-30, 'K'),
        T1 = (1e+30, 'K'),
        efficiencies = {'OO': 7.7, 'O=C=O': 1.6, 'O': 7.5, '[H][H]': 3.7, '[He]': 0.65, '[O][O]': 1.2, 'N#N': 1.5, '[C-]#[O+]': 2.8},
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 20,
    label = "H + H2O2 <=> OH + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.41e+13, 'cm^3/(mol*s)'), n=0, Ea=(3970, 'cal/mol'), T0=(1, 'K')),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 21,
    label = "H + H2O2 <=> H2 + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.82e+13, 'cm^3/(mol*s)'), n=0, Ea=(7950, 'cal/mol'), T0=(1, 'K')),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 22,
    label = "O + H2O2 <=> OH + HO2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.55e+06, 'cm^3/(mol*s)'), n=2, Ea=(3970, 'cal/mol'), T0=(1, 'K')),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 23,
    label = "OH + H2O2 <=> H2O + HO2",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = MultiArrhenius(
        arrhenius = [
            Arrhenius(A=(1.74e+12, 'cm^3/(mol*s)'), n=0, Ea=(318, 'cal/mol'), T0=(1, 'K')),
            Arrhenius(A=(7.59e+13, 'cm^3/(mol*s)'), n=0, Ea=(7270, 'cal/mol'), T0=(1, 'K')),
        ],
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 24,
    label = "H + HO2 <=> O + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (2.9e+08, 'cm^3/(mol*s)'),
        n = 1.55,
        Ea = (-160.1, 'cal/mol'),
        T0 = (1, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 25,
    label = "H + HO2 <=> H2O2",
    degeneracy = 1.0,
    kinetics = ThirdBody(
        arrheniusLow = Arrhenius(
            A = (6e+14, 'cm^6/(mol^2*s)'),
            n = 1.25,
            Ea = (-270, 'cal/mol'),
            T0 = (1, 'K'),
        ),
        efficiencies = {},
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 26,
    label = "OH + OH <=> O2 + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+11, 'cm^3/(mol*s)'), n=0.51, Ea=(50500, 'cal/mol'), T0=(1, 'K')),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 27,
    label = "O + H2O <=> O2 + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (1.07e+10, 'cm^3/(mol*s)'),
        n = 0.97,
        Ea = (68700, 'cal/mol'),
        T0 = (1, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 28,
    label = "O + H2O2 <=> O2 + H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.43e+11, 'cm^3/(mol*s)'), n=0, Ea=(3970, 'cal/mol'), T0=(1, 'K')),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 29,
    label = "O + OH <=> HO2",
    degeneracy = 1.0,
    kinetics = ThirdBody(
        arrheniusLow = Arrhenius(A=(1e+15, 'cm^6/(mol^2*s)'), n=0, Ea=(0, 'cal/mol'), T0=(1, 'K')),
        efficiencies = {},
    ),
    longDesc = 
u"""
Originally from reaction library: BurkeH2O2inN2
""",
)

entry(
    index = 30,
    label = "CO + O <=> CO2",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Lindemann(
        arrheniusHigh = Arrhenius(A=(1.88e+11, 'cm^3/(mol*s)'), n=0, Ea=(2430, 'cal/mol'), T0=(1, 'K')),
        arrheniusLow = Arrhenius(
            A = (1.4e+21, 'cm^6/(mol^2*s)'),
            n = -2.1,
            Ea = (5500, 'cal/mol'),
            T0 = (1, 'K'),
        ),
        efficiencies = {'C': 2, 'CO': 3, 'O=C=O': 3.8, 'CC': 3, 'O': 12, 'C=O': 2.5, '[He]': 2.5, '[C-]#[O+]': 1.9, '[Ar]': 0.87},
    ),
    longDesc = 
u"""
Originally from reaction library: FFCM1(-)
""",
)

entry(
    index = 31,
    label = "CO + OH <=> CO2 + H",
    degeneracy = 1.0,
    kinetics = MultiArrhenius(
        arrhenius = [
            Arrhenius(A=(61870, 'cm^3/(mol*s)'), n=2.053, Ea=(-356, 'cal/mol'), T0=(1, 'K')),
            Arrhenius(
                A = (5.017e+12, 'cm^3/(mol*s)'),
                n = -0.664,
                Ea = (332, 'cal/mol'),
                T0 = (1, 'K'),
            ),
        ],
    ),
    longDesc = 
u"""
Originally from reaction library: FFCM1(-)
""",
)

entry(
    index = 32,
    label = "CO + HO2 <=> CO2 + OH",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (157000, 'cm^3/(mol*s)'),
        n = 2.18,
        Ea = (17944, 'cal/mol'),
        T0 = (1, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: FFCM1(-)
""",
)

entry(
    index = 33,
    label = "CO + O2 <=> CO2 + O",
    degeneracy = 1.0,
    kinetics = Arrhenius(
        A = (1.533e+12, 'cm^3/(mol*s)'),
        n = 0,
        Ea = (47700, 'cal/mol'),
        T0 = (1, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: FFCM1(-)
""",
)

entry(
    index = 34,
    label = "[CH]1C=C[CH]CCC1 <=> C7H10",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [7.77282, 0.792117, -0.206702, 0.00847509],
            [1.02143, 1.00712, -0.169062, -0.0540197],
            [-0.471717, 0.451469, 0.0605186, -0.0167321],
            [-0.47741, 0.20358, 0.0844826, 0.0269059],
            [-0.284927, 0.125192, 0.0175704, 0.0191254],
            [-0.131212, 0.0946967, -0.00620185, -0.00186228],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 35,
    label = "C7H10 <=> C1=CC2CCCC12",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [-0.340598, 0.552457, -0.114671, -0.0026564],
            [8.79588, 0.919065, -0.160942, -0.0167519],
            [-0.53455, 0.537967, -0.0379394, -0.0276801],
            [-0.297403, 0.235209, 0.0305079, -0.0189152],
            [-0.169879, 0.103808, 0.0309201, -0.00258223],
            [-0.115972, 0.0718371, 0.0110305, 0.00463352],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 36,
    label = "[CH]1C=C[CH]CCC1 <=> C1=CC2CCCC12",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [8.62347, 2.332, -0.229174, -0.0456973],
            [-0.414776, 0.641543, -0.0154792, -0.0433183],
            [-0.637663, 0.208634, 0.0822427, -0.0248382],
            [-0.4181, 0.0674665, 0.050322, 0.0184925],
            [-0.300115, 0.0747453, -0.00696038, 0.0286291],
            [-0.19034, 0.0687099, -0.0230732, 0.0107207],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 37,
    label = "C7H10 + O2 <=> O2 + [CH]1C=C[CH]CCC1",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [-4.06506, -8.3866e-05, -5.83748e-05, -3.2411e-05],
            [12.9094, 1.76323e-05, 1.22725e-05, 6.81354e-06],
            [0.0693079, -2.2024e-06, -1.53289e-06, -8.51011e-07],
            [0.0472468, 5.45254e-07, 3.79485e-07, 2.10663e-07],
            [0.0220168, -3.61516e-07, -2.51624e-07, -1.39699e-07],
            [0.00979976, -4.59079e-07, -3.19531e-07, -1.77401e-07],
        ],
        kunits = 'cm^3/(mol*s)',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 38,
    label = "C=CC=CC1CC1 <=> C7H10",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [-1.27368, 0.361462, -0.196206, -0.0461776],
            [10.9162, 1.10028, -0.0408687, 0.0225523],
            [-0.759309, 0.606207, -0.0442111, -0.00648963],
            [-0.505645, 0.27604, -0.00356844, -0.0128774],
            [-0.274848, 0.125986, 0.0213559, -0.00253398],
            [-0.159497, 0.0602568, 0.0123202, 0.0029581],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 39,
    label = "[CH]1C=C[CH]CCC1 <=> C=CC=CC1CC1",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [0.437119, 1.62186, 0.0677002, -0.107712],
            [8.84095, 1.20451, -0.206424, 0.0365431],
            [-0.898246, 0.435998, -0.00597326, 0.0254851],
            [-0.786777, 0.227876, 0.00585469, -0.00270586],
            [-0.403299, 0.0633779, 0.0192995, 0.0079696],
            [-0.160205, -0.000559391, 0.00684342, 0.00525475],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 40,
    label = "C=CC=CC1CC1 <=> C1=CC2CCCC12",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [-3.46946, -0.470353, -0.457261, -0.0472892],
            [11.6122, 1.76244, 0.00893278, -0.0503406],
            [-0.682561, 0.644989, 0.0110779, 0.00312363],
            [-0.58662, 0.238978, 0.00512696, 0.00415153],
            [-0.342079, 0.147511, 0.0241895, -0.00141868],
            [-0.173376, 0.0973009, 0.0228697, -0.000164548],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 41,
    label = "[CH2]C=CC=CC[CH2] <=> C7H10",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [8.29238, 1.8684, -0.177638, -0.043687],
            [-0.139636, 0.471933, -0.0265391, 0.0303945],
            [-0.466536, 0.423965, -0.101709, -0.00163645],
            [-0.364678, 0.35132, -0.0281257, -0.0268572],
            [-0.280594, 0.182199, 0.0568721, -0.0173343],
            [-0.148698, 0.0375697, 0.0500641, 0.00527491],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 42,
    label = "[CH2]C=CC=CC[CH2] <=> [CH]1C=C[CH]CCC1",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [2.0685, 2.85012, 0.124291, -0.0793598],
            [1.67905, 0.337934, -0.231434, 0.0528779],
            [-0.583586, 0.167713, -0.0737867, 0.0367512],
            [-0.648041, 0.299818, -0.0106565, -0.0329965],
            [-0.380376, 0.0939323, 0.0555123, -0.0124418],
            [-0.110647, -0.0291756, 0.0268512, 0.00715385],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 43,
    label = "[CH2]C=CC=CC[CH2] <=> C=CC=CC1CC1",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [9.19443, 2.17989, -0.187744, -0.0437073],
            [-0.910708, 0.885737, 0.00426049, 0.0220993],
            [-0.715311, 0.393583, -0.0223159, -0.00306687],
            [-0.315617, 0.13599, 0.0107221, -0.0128532],
            [-0.175521, 0.0409489, 0.0308994, -0.0036481],
            [-0.0972562, 0.0108838, 0.016646, 0.00299592],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 44,
    label = "[CH2]C=CC=CC[CH2] <=> C1=CC2CCCC12",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [6.11201, 1.01627, -0.432717, -0.0464224],
            [0.639376, 1.14646, 0.023176, -0.0471855],
            [-0.37059, 0.482444, -0.0369909, 0.00693289],
            [-0.463115, 0.310301, -0.00734406, -0.00479774],
            [-0.362185, 0.183018, 0.064247, -0.00954281],
            [-0.165914, 0.0596256, 0.0569738, 0.00474729],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 45,
    label = "C7H10 <=> C=CC1C=CCC1",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [-11.529, 0.0544618, -0.203366, -0.0396561],
            [21.0084, 0.72656, -0.106145, 0.0387669],
            [-0.431521, 0.635125, -0.128976, -0.00500681],
            [-0.504647, 0.425106, -0.0155883, -0.0325293],
            [-0.314763, 0.17651, 0.0699747, -0.0145551],
            [-0.159968, 0.0312753, 0.0449418, 0.0116142],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 46,
    label = "C=CC=CC1CC1 <=> C=CC1C=CCC1",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [-1.40636, 0.378074, -0.212875, -0.0416139],
            [10.9634, 1.12686, -0.0711472, 0.0282687],
            [-0.711352, 0.610363, -0.0578683, -0.00441353],
            [-0.46931, 0.261771, -0.00521205, -0.0129779],
            [-0.244428, 0.104598, 0.0245167, -0.00325786],
            [-0.136076, 0.0417445, 0.0156735, 0.00253712],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 47,
    label = "[CH]1C=C[CH]CCC1 <=> C=CC1C=CCC1",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [-0.500123, 1.22366, 0.0688029, -0.0932578],
            [9.63608, 0.74437, -0.267521, 0.0685115],
            [-0.683805, 0.514239, -0.100976, 0.0205645],
            [-0.823271, 0.39362, 0.000850569, -0.0321371],
            [-0.424318, 0.100322, 0.0638042, -0.00495257],
            [-0.130518, -0.0210923, 0.0215061, 0.0118389],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 48,
    label = "[CH2]C=CC=CC[CH2] <=> C=CC1C=CCC1",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [8.18529, 1.86373, -0.19204, -0.0403514],
            [-0.0481206, 0.480922, -0.0617379, 0.037159],
            [-0.381395, 0.401503, -0.105912, -0.00491608],
            [-0.309568, 0.322064, -0.0196593, -0.0311929],
            [-0.236845, 0.14763, 0.0689714, -0.0201948],
            [-0.120504, 0.0161504, 0.0546796, 0.00581388],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 49,
    label = "C=C[C]1C[CH]CC1 <=> C7H10",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [-0.81349, -0.0642226, -0.381426, -0.0929922],
            [7.93541, 1.39652, -0.0154693, 0.0446165],
            [-0.414794, 0.956072, -0.050268, 0.00323599],
            [-0.789507, 0.421397, 0.0539021, -0.0242212],
            [-0.437905, 0.0641438, 0.0724368, 0.00555839],
            [-0.175382, -0.00855953, 0.00942294, 0.0166814],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 50,
    label = "C=C[C]1C[CH]CC1 <=> [CH]1C=C[CH]CCC1",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [-6.65396, 1.08864, -0.150575, -0.153626],
            [9.28921, 1.09313, -0.174576, 0.106184],
            [-0.628593, 0.750585, -0.0410467, 0.01139],
            [-1.01791, 0.35026, 0.0626065, -0.0260238],
            [-0.502701, 0.0137469, 0.0657198, 0.00939642],
            [-0.133254, -0.0314598, 0.00182272, 0.00911216],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 51,
    label = "C=C[C]1C[CH]CC1 <=> C=CC=CC1CC1",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [-0.0570114, 0.321136, -0.405116, -0.0912791],
            [7.10535, 1.7773, 0.0278412, 0.0324913],
            [-0.55461, 0.808744, 0.0267622, 0.00664751],
            [-0.655962, 0.23049, 0.0401254, -0.0047946],
            [-0.341127, 0.0328566, 0.0283551, 0.00347121],
            [-0.157652, 0.014143, 0.00771578, 0.00252989],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 52,
    label = "[CH2]C=CC=CC[CH2] <=> C=C[C]1C[CH]CC1",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [3.51093, 1.76086, -0.321754, -0.0951697],
            [2.56656, 0.769045, -0.0289587, 0.0549616],
            [-0.142074, 0.635542, -0.0482059, -0.0066293],
            [-0.5505, 0.308638, 0.0681899, -0.0313042],
            [-0.352101, 0.0205052, 0.094039, 0.00183624],
            [-0.13692, -0.0352723, 0.0224993, 0.0209681],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 53,
    label = "C=C[C]1C[CH]CC1 <=> C=CC1C=CCC1",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [7.93453, 1.42299, -0.207765, -0.010268],
            [0.840032, 0.931858, -0.0570854, -0.0254449],
            [-0.677283, 0.477542, 0.05482, -0.00300822],
            [-0.336484, 0.189151, 0.00370383, 0.0190998],
            [-0.165341, 0.084956, -0.0144747, 0.00534234],
            [-0.103945, 0.0530385, -0.000477753, -0.00500588],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

entry(
    index = 54,
    label = "C=C[C]1C[CH]CC1 <=> C1=CC2CCCC12",
    degeneracy = 1.0,
    kinetics = Chebyshev(
        coeffs = [
            [-2.87415, -0.809193, -0.624008, -0.100106],
            [8.65162, 2.07001, 0.0541994, -0.0246571],
            [-0.396514, 0.952601, 0.00202845, 0.0202903],
            [-0.897544, 0.350562, 0.0557342, -0.00511026],
            [-0.508461, 0.0696478, 0.0677382, 0.00469848],
            [-0.18754, 0.0269118, 0.0168361, 0.0107044],
        ],
        kunits = 's^-1',
        Tmin = (300, 'K'),
        Tmax = (3000, 'K'),
        Pmin = (0.01, 'bar'),
        Pmax = (100, 'bar'),
    ),
)

